use gpui::{AnyElement, Context, FontWeight, IntoElement, div, prelude::*, px, svg};

use super::LibraryView;
use crate::theme;

impl LibraryView {
    pub(super) fn render_playlists(&self, _cx: &mut Context<Self>) -> AnyElement {
        div()
            .flex()
            .flex_col()
            .flex_1()
            .min_h_0()
            .w_full()
            .px(px(28.))
            .pt(px(26.))
            .pb(px(24.))
            .child(
                div()
                    .flex()
                    .items_start()
                    .justify_between()
                    .w_full()
                    .min_h(px(63.))
                    .pb(px(10.))
                    .flex_none()
                    .child(
                        div()
                            .flex()
                            .flex_col()
                            .child(
                                div()
                                    .font_family(theme::FONT_DISPLAY)
                                    .font_weight(FontWeight::BOLD)
                                    .text_size(px(34.))
                                    .text_color(theme::text_primary())
                                    .child("Playlists"),
                            )
                            .child(
                                div()
                                    .font_family(theme::FONT_SANS)
                                    .text_size(px(13.))
                                    .text_color(theme::text_secondary())
                                    .child("Your saved collections"),
                            ),
                    )
                    .child(render_disabled_new_playlist()),
            )
            .child(
                div()
                    .flex()
                    .flex_1()
                    .min_h_0()
                    .w_full()
                    .gap(px(18.))
                    .child(
                        div()
                            .flex()
                            .flex_col()
                            .w(px(390.))
                            .h_full()
                            .flex_none()
                            .overflow_hidden()
                            .rounded(px(theme::RADIUS_MD))
                            .border_1()
                            .border_color(theme::border())
                            .bg(theme::bg_surface())
                            .child(
                                div()
                                    .flex()
                                    .items_center()
                                    .h(px(45.))
                                    .flex_none()
                                    .px(px(16.))
                                    .border_b_1()
                                    .border_color(theme::border())
                                    .font_family(theme::FONT_MONO)
                                    .font_weight(FontWeight::BOLD)
                                    .text_size(px(10.))
                                    .text_color(theme::text_muted())
                                    .child("PLAYLISTS"),
                            )
                            .child(render_playlist_empty()),
                    )
                    .child(
                        div()
                            .flex()
                            .flex_1()
                            .min_w_0()
                            .h_full()
                            .items_center()
                            .justify_center()
                            .rounded(px(theme::RADIUS_MD))
                            .border_1()
                            .border_color(theme::border())
                            .bg(theme::bg_surface_alt())
                            .child(
                                div()
                                    .flex()
                                    .flex_col()
                                    .items_center()
                                    .child(
                                        svg()
                                            .path("icons/list-music.svg")
                                            .size(px(34.))
                                            .text_color(theme::text_muted()),
                                    )
                                    .child(
                                        div()
                                            .mt(px(13.))
                                            .font_family(theme::FONT_DISPLAY)
                                            .font_weight(FontWeight::SEMIBOLD)
                                            .text_size(px(18.))
                                            .text_color(theme::text_secondary())
                                            .child("Select a playlist"),
                                    )
                                    .child(
                                        div()
                                            .mt(px(4.))
                                            .font_family(theme::FONT_SANS)
                                            .text_size(px(12.))
                                            .text_color(theme::text_muted())
                                            .child("Playlist creation arrives in the next stage."),
                                    ),
                            ),
                    ),
            )
            .into_any_element()
    }
}

fn render_playlist_empty() -> impl IntoElement {
    div()
        .flex()
        .flex_col()
        .flex_1()
        .items_center()
        .justify_center()
        .px(px(28.))
        .child(
            div()
                .flex()
                .items_center()
                .justify_center()
                .size(px(54.))
                .rounded_full()
                .bg(theme::bg_muted())
                .child(
                    svg()
                        .path("icons/list-music.svg")
                        .size(px(25.))
                        .text_color(theme::text_muted()),
                ),
        )
        .child(
            div()
                .mt(px(15.))
                .font_family(theme::FONT_DISPLAY)
                .font_weight(FontWeight::SEMIBOLD)
                .text_size(px(18.))
                .text_color(theme::text_primary())
                .child("No playlists yet"),
        )
        .child(
            div()
                .mt(px(5.))
                .max_w(px(250.))
                .text_center()
                .font_family(theme::FONT_SANS)
                .text_size(px(12.))
                .text_color(theme::text_muted())
                .child("Build collections from your library when playlist support lands."),
        )
        .child(render_disabled_new_playlist().mt(px(18.)))
}

fn render_disabled_new_playlist() -> gpui::Div {
    div()
        .flex()
        .items_center()
        .gap(px(7.))
        .h(px(34.))
        .px(px(12.))
        .rounded(px(theme::RADIUS_SM))
        .border_1()
        .border_color(theme::border())
        .bg(theme::bg_muted())
        .opacity(0.55)
        .child(
            svg()
                .path("icons/plus.svg")
                .size(px(15.))
                .text_color(theme::text_muted()),
        )
        .child(
            div()
                .font_family(theme::FONT_DISPLAY)
                .font_weight(FontWeight::SEMIBOLD)
                .text_size(px(13.))
                .text_color(theme::text_secondary())
                .child("New Playlist"),
        )
}
